"""add on delete cascade to user_permissions

Revision ID: 1ae23610d11e
Revises: c1d0aaa2276d
Create Date: 2023-07-25 11:18:58.497497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae23610d11e'
down_revision = 'c1d0aaa2276d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_permissions_permission_id_fkey', 'user_permissions', type_='foreignkey')
    op.drop_constraint('user_permissions_user_id_fkey', 'user_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_permissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permissions', type_='foreignkey')
    op.drop_constraint(None, 'user_permissions', type_='foreignkey')
    op.create_foreign_key('user_permissions_user_id_fkey', 'user_permissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_permissions_permission_id_fkey', 'user_permissions', 'permissions', ['permission_id'], ['id'])
    # ### end Alembic commands ###
