"""add user, permission, group unique constraints

Revision ID: 2e5063abade7
Revises: b0aacda45305
Create Date: 2023-07-25 15:18:20.696087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5063abade7'
down_revision = 'b0aacda45305'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'groups', ['group_name'])
    op.create_unique_constraint(None, 'permissions', ['permission_name'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'groups', type_='unique')
    # ### end Alembic commands ###
