"""test out nicely formatted migration file name

Revision ID: 4bfa8cd3a5e7
Revises: 1ae23610d11e
Create Date: 2023-07-25 11:54:54.537583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfa8cd3a5e7'
down_revision = '1ae23610d11e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
