"""6th migration

Revision ID: 4f1f1c91c6f0
Revises: d7a983dea1f5
Create Date: 2023-07-07 01:47:37.196880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1f1c91c6f0'
down_revision = 'd7a983dea1f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emotions") as batch_op:
        batch_op.drop_column('sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotions', sa.Column('sample', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
