"""4th migration

Revision ID: 5ee0a5831a41
Revises: 90bb7fd9e7d5
Create Date: 2023-07-07 01:45:04.447558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee0a5831a41'
down_revision = '90bb7fd9e7d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emotions") as batch_op:
        batch_op.drop_column('namechange')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotions', sa.Column('namechange', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
