"""3rd migration

Revision ID: 90bb7fd9e7d5
Revises: cd1819ee964a
Create Date: 2023-06-27 12:54:18.238120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bb7fd9e7d5'
down_revision = 'cd1819ee964a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emotions") as batch_op:
        batch_op.drop_column('ex_one')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotions', sa.Column('ex_one', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
