"""2nd migration

Revision ID: cd1819ee964a
Revises: 41e20963b88c
Create Date: 2023-06-27 12:53:54.757614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1819ee964a'
down_revision = '41e20963b88c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotions', sa.Column('ex_one', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emotions', 'ex_one')
    # ### end Alembic commands ###
