"""5th migration

Revision ID: d7a983dea1f5
Revises: 5ee0a5831a41
Create Date: 2023-07-07 01:46:42.499784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a983dea1f5'
down_revision = '5ee0a5831a41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotions', sa.Column('sample', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emotions', 'sample')
    # ### end Alembic commands ###
